# Fail on error or unbounded variable
set -euo pipefail

# cleanup
rm -rf obj_dir
rm -f sigdelay.vcd

# run Verilator to trnanslate Verilog into C++, incuding the C++ testbench
verilator -Wall --cc --trace sigdelay.sv --exe sigdelay_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsigdelay.mk Vsigdelay

# run exec
obj_dir/Vsigdelay
