# cleanup

set -euo pipefail

rm -rf obj_dir
rm -f sinegen.vcd

# run Verilator to trnanslate Verilog into C++, incuding the C++ testbench
verilator -Wall --cc --trace sinegen.sv --exe sinegen_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vsinegen.mk Vsinegen

# run exec
obj_dir/Vsinegen
